using System.Collections.Immutable;
using System.Composition;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CodeActions;
using Microsoft.CodeAnalysis.CodeFixes;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace GameDialog.CodeFix;

[ExportCodeFixProvider(LanguageNames.CSharp, Name = nameof(ReplaceWithDialogTextLabelCodeFixProvider)), Shared]
public class ReplaceWithDialogTextLabelCodeFixProvider : CodeFixProvider
{
    public override ImmutableArray<string> FixableDiagnosticIds => ["DIA001"];

    public override FixAllProvider GetFixAllProvider() => WellKnownFixAllProviders.BatchFixer;

    public override async Task RegisterCodeFixesAsync(CodeFixContext context)
    {
        Diagnostic? diagnostic = context.Diagnostics.FirstOrDefault();

        if (diagnostic is null)
            return;

        context.RegisterCodeFix(
            CodeAction.Create(
                title: "Replace document with DialogTextLabel",
                equivalenceKey: "Replace document with DialogTextLabel",
                createChangedDocument: ct => ReplaceDocumentAsync(context.Document, ct)
            ),
            diagnostic);
    }

    private async Task<Document> ReplaceDocumentAsync(Document targetDocument, CancellationToken ct)
    {
        SyntaxNode? root = await targetDocument.GetSyntaxRootAsync(ct);

        if (root is null)
        {
            SourceText origText = await targetDocument.GetTextAsync(ct);
            return targetDocument.WithText(origText);
        }

        ClassDeclarationSyntax cds = root.DescendantNodes()
            .OfType<ClassDeclarationSyntax>()
            .FirstOrDefault();
        string className = cds.Identifier.Text;
        string ns = GetDeclaredNamespace(root);
        string replacementText = FindDialogTextLabelDocumentAsync();
        replacementText = "// <auto-generated />\n#nullable enable\nusing GameDialog.Runner;\n" + replacementText;
        replacementText = replacementText.Replace("namespace GameDialog.Runner", ns.Length > 0 ? $"namespace {ns}" : "");

        if (className.Length > 0)
            replacementText = replacementText.Replace("DialogTextLabel", className);

        SourceText newSource = SourceText.From(replacementText, Encoding.UTF8);
        return targetDocument.WithText(newSource);
    }

    private static string GetDeclaredNamespace(SyntaxNode? root)
    {
        var ns = root?.DescendantNodes()
            .OfType<BaseNamespaceDeclarationSyntax>()
            .FirstOrDefault(n => n.DescendantNodes().OfType<TypeDeclarationSyntax>().Any());

        return ns?.Name.ToString() ?? string.Empty;
    }

    private string FindDialogTextLabelDocumentAsync()
    {
        var assembly = Assembly.GetExecutingAssembly();
        string resourceName = "GameDialog.CodeFix.Resources.DialogTextLabel.cs";
        using Stream stream = assembly.GetManifestResourceStream(resourceName);

        if (stream == null)
            return string.Empty;

        using StreamReader reader = new(stream);
        return reader.ReadToEnd();
    }
}